#!/bin/bash

BRANCH="`git branch --show-current`"

rm -r ./out/ &> /dev/null
dotnet pack -c Release -o ./out src/*.csproj

if [ $BRANCH = "main" ]
then
	dotnet nuget push out/*.nupkg -s nuget.org
else
	dotnet nuget push out/*.nupkg -s github
fi
