#!/bin/bash

# Get data from git
BRANCH="`git branch --show-current`"

# Get conf data
TILED_VERSION="`cat conf/TILED_VERSION`"

# Determine if to push and to where
if [ $BRANCH = "main" ]
then
    echo "Pushing to nuget.org"
	git tag "tiled-$TILED_VERSION"
	git push origin "tiled-$TILED_VERSION"
	dotnet nuget push *.nupkg -s nuget.org -k $NUGET_API_KEY 1> /dev/null
	exit
fi

if [ $BRANCH = "develop" ]
then
    echo "Pushing to github"
	dotnet nuget push *.nupkg -s github 1> /dev/null
	exit 
fi

echo "Pushing package not allowed on branch $BRANCH"
exit 1
